### ISSUE TITLE
Palette picker

### ISSUE THREAD

**Issue by pvictor** [gabrifc/raincloud-shiny#12]
Hi,
Nice project! 
Last release of `shinyWidgets` on CRAN use new version of `bootstrap-select` and it implies some differences with the old behaviour, to make the palette picker works again, you can add somewhere in your UI this line : 

```r
tags$style(".bootstrap-select .dropdown-menu li a span.text {width: 100%;}")
```
(no better solution for the moment)

And maybe remove padding in the content : 

```r
"<div style='width:100%%;border-radius:4px;background:%s;color:%s'>%s</div>"
# instead of 
"<div style='width:100%%;padding:5px;border-radius:4px;background:%s;color:%s'>%s</div>"
```

Cheers,

Victor

**Comment by gabrifc** [comment]
Thanks Victor 👍.

I reduced the padding to 2px, imho it looks better and can't find any system where it breaks.

Please let me know if that fixes it for you also and thanks for the feedback :)
